# Generated by Django 4.1.2 on 2022-10-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_mid', models.BigIntegerField()),
                ('msg_send_uid', models.BigIntegerField()),
                ('msg_recv_uid', models.BigIntegerField()),
                ('msg_send_date', models.DateTimeField(verbose_name='msg published')),
                ('msg_type', models.IntegerField()),
                ('text', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
    ]
