# Generated by Django 4.1.2 on 2022-10-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speak_send', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_mid',
            new_name='mid',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_recv_uid',
            new_name='recv_uid',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_send_date',
            new_name='send_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_send_uid',
            new_name='send_uid',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_type',
            new_name='type',
        ),
    ]
